### ISSUE TITLE
Guest can browse public content / profiles

### ISSUE THREAD

**Issue by tgisg** [tgisg/filedrop#12]

**Comment by bcgoss** [comment]
As a visitor
When I visit a link to a public folder
I should see the files in it.

**Comment by bcgoss** [comment]
As a visitor
When I visit a link to a file in a public folder
and I click a download link or button
I should receive the file.

**Comment by bcgoss** [comment]
As a visitor
When I visit the site
I should see a list of public folders
and I should see a list of public profiles.
