### ISSUE TITLE
Guest can login or create an account

### ISSUE THREAD

**Issue by tgisg** [tgisg/filedrop#13]

**Comment by bcgoss** [comment]
As a visitor,
When I visit the site
I should see a “login” link or button
And I should see a “sign up” link or button.

**Comment by bcgoss** [comment]
As a visitor
When I visit the site
and I click “login”
and I enter my email and password
I should be logged in.
And I should see my dashboard page.

**Comment by bcgoss** [comment]
As a Visitor
When I visit the site
and I click “sign up”
and I enter my information
I should receive a text message confirmation
and I should be logged in
and I should see my dashboard page.
