### ISSUE TITLE
Registered User can invite other users to contribute to public or private folders

### ISSUE THREAD

**Issue by tgisg** [tgisg/filedrop#16]
As a Registered User
When I visit a folder path that belongs to another user
And I do not have access to that folder
I should see a 404 message

**Comment by bcgoss** [comment]
As a registered User
When I visit a folder path that belongs to another user
And I do have access to that folder
I should see it's content
And I should see options to manage that folder
and I should see options to add content
And I should not see an option to delete that folder.
