### ISSUE TITLE
Platform Admin Can Take a user online / offline and also associated content without removing any of the data from the database

### ISSUE THREAD

**Issue by tgisg** [tgisg/filedrop#6]
-As a platform admin who is logged in
-When I click on dashboard
-Then I should be on /dashboard
-And I should see a link to view all users
-And when I click "View All Users"
-Then I should be on /all_users
-Then I should see a list of all users with a description of their status and with links to -activate or deactivate each user
-And users who are active should only have the link to deactivate
-And users who are inactive should only have the link to activate
-And when I click "Deactivate" on an active user
-Then I should see a message stating that the user (and the user's content) has been deactivated
-And when I click "Activate" on a deactivated user
-Then I should see a message stating that the user (and the user's content) has been activated
-Then I should be sent back to /all_users
-And I should see a list of all users with their status updated

**Comment by tgisg** [comment]
I would appreciate any feedback. :)

**Comment by bcgoss** [comment]
See my notes on deleting content :). You've produced good stories Sonia! Thanks!
