### ISSUE TITLE
A public folder can be created by a registered user

### ISSUE THREAD

**Issue by tgisg** [tgisg/filedrop#8]

**Comment by MDes41** [comment]
As a registered user
I visit the dashboard page
I click on a public folder
I click on add file
I attach a file
I click on upload file
I am then redirected to a public folder I uploaded to

**Comment by tgisg** [comment]
Hey Matt, this looks good. The only thing I would suggest is changing the language a tad to fit the spec. So "As a registered user, when I visit the dashboard page, and I click on a public folder, and I click on add file...then I am..." etc.
